[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle dynamic routes and SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Ensure invite links work properly
[[redirects]]
  from = "/invite/*"
  to = "/invite/[uniqueGuestId].html"
  status = 200
  force = false
